import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
<meta name="Cross-Origin-Opener-Policy" content="same-origin"></meta>

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Expense Tracker App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body className={inter.className}>
        {children}
        <Toaster position={"top-center"} theme={"dark"} />
      </body>
    </html>
  );
}
